SEED: 7
DEBUG: False
SAVE_CHECKPOINTS: [10]
INFERENCE_CHECKPOINT: 10

LOGGING:
  FREQUENCY: 100
  MAX_SAMPLES: 1000

CHANGE_DETECTION:
  ENDTOEND: False

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 10
  OPTIMIZER: 'adamw'

MODEL:
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  NUM_WORKER: 2
  SHUFFLE: True
  YEAR: 2020
  SITES: ['kigali']
  SPECTRAL_BANDS: ['B4', 'B3', 'B2', 'B8']
  SEASON: 'wet'
  INCLUDE_UNLABELED: False

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  RESIZE: False