SEED: 7
DEBUG: False
SAVE_CHECKPOINTS: [10]
INFERENCE_CHECKPOINT: 10

LOGGING:
  FREQUENCY: 100
  MAX_SAMPLES: 1000

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 256
  EPOCHS: 10
  OPTIMIZER: 'adamw'

PRETRAINING:
  ENABLED: True
  CFG_NAME: 'wet2020'
  EPOCH: 10

MODEL:
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  NUM_WORKER: 2
  SHUFFLE: True
  SITES: ['kigali']
  SPECTRAL_BANDS: ['B4', 'B3', 'B2', 'B8']
  YEAR: 2020
  SEASON: 'wet'

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  RESIZE: False