_BASE_: "base_popgrowthmapping.yaml"

TRAINER:
  LR: 1e-4

CHANGE_DETECTION:
  PRETRAINING:
    ENABLED: True
    CFG_NAME: 'popmapping_test1val2train3'
    FREEZE_ENCODER: True

DATALOADER:
  TEST: 'fold1'
  VAL: 'fold2'
  TRAIN: 'fold3'